# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5741bc0eef0524bc30e5bcdd8921703e9f5b0818d5268b0f9a426ba10f91238745330cf7438c27c561a63cb28e93f5dde8c4e9df431c0ba02b2c85dbc94dcad

test:
  secret_key_base: 33e09c7adfe05abde3de448cd265a46bd01fbaa263294b483d836a553df762246800523c77692f70da398f7704bf6dbf5b366fd6f59d014a6cd873bc7a3f2305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
